export enum ICONS {
  arrowLeft = 'arrowLeft',
  arrowRight = 'arrowRight',
  bookmark2 = 'bookmark2',
  bookmark = 'bookmark',
  clock = 'clock',
  edit = 'edit',
  home = 'home',
  location = 'location',
  minusBorder = 'minusBorder',
  more = 'more',
  notification = 'notification',
  play = 'play',
  plusBorder = 'plusBorder',
  plus = 'plus',
  profile = 'profile',
  profiles = 'profiles',
  recipe = 'recipe',
  search = 'search',
  star = 'star',
}
