export default Object.freeze({
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  // Common Screens
  HOME_ROOT: 'HOME_ROOT',
  HOME_SCREEN: 'HOME_SCREEN',
  MAIN_TABS_ROOT: 'MAIN_TABS_ROOT',
  MAIN_DRAWER_ROOT: 'MAIN_DRAWER_ROOT',
  // Authentication
  AUTHENTICATION_ROOT: 'AUTHENTICATION_ROOT',
  WELCOME_SCREEN: 'WELCOME_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  ALERT: 'ALERT', // Do not redirect!
});
